# dbt_project.yml
name: 'medical_warehouse'
version: '1.0.0'
config-version: 2

profile: 'medical_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medical_warehouse:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
    metrics:
      +materialized: table
      +schema: metrics

seeds:
  medical_warehouse:
    +schema: raw
    +materialized: table

tests:
  medical_warehouse:
    data_tests:
      +schema: test_results

vars:
  start_date: '2024-01-01'
  end_date: '2026-01-20'