medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres  # Change from 'sqlite' to 'postgres'
      host: localhost
      user: postgres
      pass: "password"  # Your PostgreSQL password
      port: 5432
      dbname: telegram_warehouse
      schema: medical_warehouse
      threads: 1