version: 2

models:
  - name: stg_telegram_messages
    description: "Cleaned and standardized Telegram messages"
    columns:
      - name: message_id
        description: "Unique identifier for each message"
        tests:
          - not_null
          - unique
      - name: channel_name
        description: "Name of the Telegram channel"
      - name: post_timestamp
        description: "Timestamp when the message was posted"
        tests:
          - not_null
      - name: message_text
        description: "Content of the message"
      - name: has_media
        description: "Whether the message contains media"
      - name: view_count
        description: "Number of views on the message"
        tests:
          - not_null
      - name: forward_count
        description: "Number of times the message was forwarded"

  - name: stg_telegram_channels
    description: "Channel statistics and information"
    columns:
      - name: channel_key
        description: "Surrogate key for channel dimension"
        tests:
          - not_null
          - unique
      - name: channel_name
        description: "Name of the Telegram channel"
        tests:
          - not_null
      - name: total_posts
        description: "Total number of posts from this channel"
        tests:
          - not_null